image:
  repository: apache/druid
  tag: "29.0.1"
  pullPolicy: IfNotPresent

# Deep Storage Configuration
# For single-node K8s clusters, hostPath provides shared storage across pods
# For multi-node clusters, use S3/GCS/Azure or NFS instead
deepStorage:
  hostPath:
    enabled: true
    path: "/mnt/druid-deep-storage"

metrics:
  enabled: false
  service:
    port: 9876
  podMonitor:
    enabled: true

service:
  # Override druid_host on statefulsets to resolve components IP with DNS
  resolveWithDNS: true

extensions:
  loadList:
    - druid-datasketches
    - druid-histogram
    - druid-kubernetes-extensions
    - druid-lookups-cached-global
    - druid-parquet-extensions
    - druid-stats
    - postgresql-metadata-storage
    - druid-multi-stage-query
    # - druid-basic-security  # Basic authentication (commented out for now)

secretEnvVars: {}

configMap:
  enabled: true

# Required if using kubernetes extensions which modify resources like 'druid-kubernetes-extensions' or 'druid-kubernetes-overlord-extensions'
rbac:
  create: true

configVars:
  ## DRUID env vars. ref: https://github.com/apache/druid/blob/master/distribution/docker/druid.sh#L29
  DRUID_LOG4J: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="WARN">
      <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout pattern="%d{ISO8601} %p [%t] %c -%notEmpty{ [%markerSimpleName]} %m%n"/>
        </Console>
      </Appenders>

      <Loggers>
        <Root level="info">
          <AppenderRef ref="Console"/>
        </Root>

        <!-- Set level="debug" to see stack traces for query errors -->
        <Logger name="org.apache.druid.server.QueryResource" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
        <Logger name="org.apache.druid.server.QueryLifecycle" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>

        <!-- Set level="debug" or "trace" to see more Coordinator details (segment balancing, load/drop rules, etc) -->
        <Logger name="org.apache.druid.server.coordinator" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>

        <!-- Set level="debug" to see low-level details about segments and ingestion -->
        <Logger name="org.apache.druid.segment" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>

        <!-- Set level="debug" to see more information about extension initialization -->
        <Logger name="org.apache.druid.initialization" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>

        <!-- Quieter logging at startup -->
        <Logger name="org.skife.config" level="warn" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
        <Logger name="com.sun.jersey.guice" level="warn" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
      </Loggers>
    </Configuration>

  # Monitoring
  # See https://druid.apache.org/docs/latest/development/extensions-contrib/prometheus.html to configure
  # TODO: Use pushgateway for indexers (avoid losing scale_interval amount of metrics + they may )
  # https://druid.apache.org/docs/latest/configuration/index.html#emitting-metrics
  druid_emitter: noop
  druid_emitter_logging_logLevel: debug

  # Storage
  # https://druid.apache.org/docs/latest/configuration/index.html#common-configurations
  druid_storage_type: local
  druid_storage_storageDirectory: "/mnt/druid-deep-storage"  # Absolute path for shared hostPath storage
  druid_indexer_logs_type: file
  druid_indexer_logs_directory: /opt/druid/var/indexing-logs  # Writable location

  # Kubernetes discovery
  druid_zk_service_enabled: "false"
  druid_serverview_type: http
  druid_coordinator_loadqueuepeon_type: http
  druid_indexer_runner_type: httpRemote
  druid_discovery_type: k8s

  druid_discovery_k8s_clusterIdentifier: "druid-demo"

  # Authentication and Authorization (DISABLED - uncomment to enable)
  # https://druid.apache.org/docs/latest/design/auth.html
  # druid_auth_authenticatorChain: '["basic"]'
  # druid_auth_authenticator_basic_type: basic
  # druid_auth_authenticator_basic_initialAdminPassword: admin123  # Change this!
  # druid_auth_authenticator_basic_initialInternalClientPassword: internal123
  # druid_auth_authenticator_basic_credentialsValidator_type: metadata
  # druid_auth_authenticator_basic_skipOnFailure: "false"
  # druid_auth_authenticator_basic_authorizerName: basic

  # druid_auth_authorizers: '["basic"]'
  # druid_auth_authorizer_basic_type: basic

  # Allow unauthenticated access to health check endpoints
  # druid_auth_unsecuredPaths: '["/status", "/status/health", "/status/selfDiscovered", "/status/selfDiscovered/status"]'

  # Escalator for internal service communication
  # druid_escalator_type: basic
  # druid_escalator_internalClientUsername: druid_system
  # druid_escalator_internalClientPassword: internal123
  # druid_escalator_authorizerName: basic

router:
  enabled: true
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    scaleDownStabilizationWindowSeconds: 300
    # targetCPU: 80
    # targetMemory: 80
    # targetMetric:
    #   name: druid_remaining_maintainer_tasks_instantaneous
    #   service:
    #   value: 7
  name: router
  port: 8888
  serviceType: NodePort  # Changed to NodePort for external access
  nodePort: 31888  # Fixed NodePort for consistent external access
  serviceExtraPorts: []
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  service: {}
    # resolveWithDNS: false
  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    enabled: false
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 15
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 5
    successThreshold: 1
  ingress:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-type: basic
      kubernetes.io/tls-acme: "false"
    path: /
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  priorityClassName: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}
  annotations: {}
  podAnnotations: {}
  podLabels: {}
  podDisruptionBudget: {}
  envVars:
    DRUID_XMX: 256m
    DRUID_XMS: 256m
    druid_router_managementProxy_enabled: "true"
  secretEnvVars: {}
  serviceAccount:
    # -- Create a service account for the broker
    create: true
    # -- Service Account name
    name:
    # -- Annotations applied to created service account
    annotations: {}
    # -- Labels applied to created service account
    labels: {}
    # -- Automount API credentials for the service account
    automountServiceAccountToken: true

broker:
  enabled: true
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    averageCpuUtilization: 80
  name: broker
  port: 8082
  serviceType: ClusterIP
  serviceExtraPorts: []
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  service: {}
    # resolveWithDNS: false
  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    enabled: false
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 60
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 30
    successThreshold: 1
  ingress:
    enabled: false
    annotations: {}
    path: /
    tls: []
  terminationGracePeriodSeconds: 10
  resources:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  priorityClassName: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}
  annotations: {}
  podAnnotations: {}
  podLabels: {}
  podDisruptionBudget: {}
  envVars:
    DRUID_XMX: 1g
    DRUID_XMS: 1g
    DRUID_MAXDIRECTMEMORYSIZE: 512m
    druid_processing_buffer_sizeBytes: '100000000'
    druid_processing_numMergeBuffers: "2"
    druid_processing_numThreads: "2"
  secretEnvVars: {}
  serviceAccount:
    # -- Create a service account for the broker
    create: true
    # -- Service Account name
    name:
    # -- Annotations applied to created service account
    annotations: {}
    # -- Labels applied to created service account
    labels: {}
    # -- Automount API credentials for the service account
    automountServiceAccountToken: true

coordinator:
  enabled: true
  replicaCount: 1
  name: coordinator
  port: 8081
  serviceType: ClusterIP
  serviceExtraPorts: []
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  service: {}
    # resolveWithDNS: false
  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    enabled: false
  ingress:
    enabled: false
    annotations: {}
    path: /
    tls: []
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 60
    failureThreshold: 15
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 60
    failureThreshold: 5
    successThreshold: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  priorityClassName: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}
  annotations: {}
  podAnnotations: {}
  podLabels: {}
  podDisruptionBudget: {}
  envVars:
    DRUID_XMX: 512m
    DRUID_XMS: 512m
    # Enable Coordinator to also run as Overlord (combined service)
    druid_coordinator_asOverlord_enabled: "true"
  secretEnvVars: {}
  serviceAccount:
    # -- Create a service account for the coordinator
    create: true
    # -- Service Account name
    name:
    # -- Annotations applied to created service account
    annotations: {}
    # -- Labels applied to created service account
    labels: {}
    # -- Automount API credentials for the service account
    automountServiceAccountToken: true

historical:
  enabled: true
  defaults:
    name: historical
    replicaCount: 2  # Scale to 2 nodes to demonstrate replication
    autoscaling:
      enabled: false
      hpa: true
      minReplicas: 1
      maxReplicas: 5
      scaleDownStabilizationWindowSeconds: 300
      # targetCPU: 80
      # targetMemory: 80
      # targetMetric:
      #   name: druid_remaining_maintainer_tasks_instantaneous
      #   service:
      #   value: 7
    port: 8083
    podManagementPolicy: Parallel
    envVars:
      # Processing
      # 100Mo
      druid_processing_buffer_sizeBytes: '100000000'
      druid_processing_numMergeBuffers: "2"
      druid_processing_numThreads: "2"
    secretEnvVars: {}
    podSecurityContext:
      fsGroup: 1000
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: true
    priorityClassName: ""
    affinity: {}
    nodeSelector: {}
    tolerations: []
    resources: {}
    updateStrategy:
      type: RollingUpdate
    # Startup may be slow if a lot of segments.
    startupProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 10
      failureThreshold: 400
      successThreshold: 1
    livenessProbe:
      enabled: true
      # We do not want to restart a historical pod too soon
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 10
      failureThreshold: 60
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 10
      failureThreshold: 30
      successThreshold: 1
    podAnnotations: {}
    podLabels: {}
    serviceAccount:
      # -- Create a service account for the coordinator
      create: true
      # -- Service Account name
      name:
      # -- Annotations applied to created service account
      annotations: {}
      # -- Labels applied to created service account
      labels: {}
      # -- Automount API credentials for the service account
      automountServiceAccountToken: true
  tiers:
    default:
      # enabled: false
      envVars:
        DRUID_XMX: 1g
        DRUID_XMS: 1g
        DRUID_MAXDIRECTMEMORYSIZE: 512m

        druid_server_tier: "_default_tier"  # Fixed to match Druid's default load rules
        druid_segmentCache_locations: '[{"path":"/opt/druid/var/druid/segment-cache","maxSize":"2GiB"}]'
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1000m
      persistence:
        size: 5Gi
      # autoscaling:
      #   enabled: false
      #   minReplicas: 1
      #   maxReplicas: 2
      #   targetCPU: 80
      #   targetMemory: 80
      #   targetMetric:
      #     name: druid_remaining_maintainer_tasks_instantaneous
      #     service:
      #     value: 7

indexer:
  enabled: true
  defaults:
    name: indexer
    replicaCount: 1
    port: 8091
    podManagementPolicy: Parallel
    updateStrategy:
      type: RollingUpdate
    service: {}
      # resolveWithDNS: false
    podSecurityContext:
      fsGroup: 1000
    containerSecurityContext:
      enabled: false
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 15
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 5
      successThreshold: 1
    priorityClassName: ""
    affinity: {}
    nodeSelector: {}
    tolerations: []
    resources: {}
    envVars: {}
    secretEnvVars: {}
    serviceAccount:
      # -- Create a service account for the coordinator
      create: true
      # -- Service Account name
      name:
      # -- Annotations applied to created service account
      annotations: {}
      # -- Labels applied to created service account
      labels: {}
      # -- Automount API credentials for the service account
      automountServiceAccountToken: true
  categories:
    default:
      # enabled: false
      envVars:
        DRUID_XMX: 1g  # Increased for Wikipedia ingestion
        DRUID_XMS: 1g  # Increased for Wikipedia ingestion
        druid_worker_capacity: "2"
        druid_worker_category: "default"
      resources:
        requests:
          memory: 1Gi  # Increased for ingestion tasks
          cpu: 250m
        limits:
          memory: 2Gi  # Increased to prevent OOMKill
          cpu: 1000m
      emptyDir:
        sizeLimit: 2Gi
      persistence:
        enabled: false
        size: "2Gi"
        storageClass: ""
        accessModes: "ReadWriteOnce"
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: "Retain"
          whenScaled: "Retain"

      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 2
        averageCpuUtilization: 80

# If using a zookeeper installed outside of this chart you must uncomment and set this line
# zkHosts: "druid-zookeeper-headless:2181"
zkHosts: ""

zookeeper:
  enabled: false
  image:
    debug: true
  podAnnotations: {}
  podLabels: {}

gCloudStorage:
  enabled: false
  secretName: google-cloud-key

mysql:
  enabled: false
  auth:
    rootPassword: mysql
    username: druid
    password: druid
    database: druid

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "latest"
  auth:
    postgresPassword: druid123
    username: druid
    password: druid123
    database: druid
  primary:
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    persistence:
      enabled: true
      size: 2Gi
      storageClass: "local-path"
  backup:
    s3:
      enabled: false
      cronJob:
        name: druid-postgresql-backup
        imagePullSecrets: []
        schedule: "0 12 * * *"
        startingDeadlineSeconds: 600
        concurrencyPolicy: "Forbid"
        failedJobsHistoryLimit: 1
        successfulJobsHistoryLimit: 1
        resources: {}
        priorityClassName: ""
      awsConfig:
        accessKeyId: ""
        secretAccessKey: ""
        bucketName: druid-postgresql-backup
        retention: "15 days"
        region: us-west-1

kube-hpa-scale-to-zero:
  enabled: false
  # args: ["--hpa-namespace", "{{ .Release.Namespace }}"]
  args: ["--hpa-namespace", "foo"]
  resources: {}

configJobs:
  enabled: true
  affinity: {}
  tolerations: []
  priorityClassName: ""
  restartPolicy: Never
  backoffLimit: 7
  ttlSecondsAfterFinished: 3600
  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    enabled: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  changeComment: ""
  dict:
    overlord-dyn-cfg:
      component:
        scheme: http
        name: coordinator
        port: 8081
        route: "/druid/indexer/v1/worker"
      payload:
        selectStrategy:
          type: "equalDistributionWithCategorySpec"
          workerCategorySpec:
            strong: true
            categoryMap:
              index_parallel:
                defaultCategory: "default"
              index:
                defaultCategory: "default"
              single_phase_sub_task:
                defaultCategory: "default"
              kill:
                defaultCategory: "default"
              compact:
                defaultCategory: "default"

extra-objects:
  enabled: false

druid-tasks-exporter:
  enabled: false
